name: Razor-qt
description: The Razor Desktop Environment
logo: images/logo.png

url: http://razor-qt.org

markdown: kramdown

redcarpet:
  # Use Github Flavored Markdown (including triple backticks)
  input: GFM

sass:
  style: :compressed

gems:
  - jekyll-sitemap

exclude:
  - LICENSE
